# Generated by Django 4.0.3 on 2022-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('frozen', models.BooleanField(default=False)),
                ('unresolved', models.BooleanField(default=False)),
            ],
        ),
    ]
